import { Prisma } from "@prisma/client";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { recordActivity, requestData, requireAdminApi, routeResponse } from "@/lib/http";

const schema = z.object({ inventoryItemId: z.string().min(1), quantity: z.number().int().positive().max(100000), lenderName: z.string().trim().min(1).max(160), takenBy: z.string().trim().min(1).max(160), borrowerPhone: z.string().max(40).nullable().optional(), rentedAt: z.string().datetime(), dueAt: z.string().datetime(), description: z.string().max(2000).nullable().optional(), conditionNote: z.string().max(2000).nullable().optional(), initialConditionPhoto: z.string().max(2048).nullable().optional(), conditionCaption: z.string().max(2000).nullable().optional() });
const clean = (value?: string | null) => value?.trim() || null;
function dates(value: z.infer<typeof schema>) { const rentedAt = new Date(value.rentedAt); const dueAt = new Date(value.dueAt); if (dueAt < rentedAt) throw new Error("INVALID_DATES"); return { rentedAt, dueAt }; }
function cleanData(value: z.infer<typeof schema>, actor: string) { return { quantity: value.quantity, lenderName: value.lenderName, takenBy: value.takenBy, borrowerPhone: clean(value.borrowerPhone), description: clean(value.description), conditionNote: clean(value.conditionNote), initialConditionPhoto: clean(value.initialConditionPhoto), conditionCaption: clean(value.conditionCaption), ...dates(value), updatedBy: actor }; }
function invalid(reason: unknown) { if (reason instanceof z.ZodError) return NextResponse.json({ error: reason.issues[0]?.message || "Dados inválidos." }, { status: 400 }); if (reason instanceof Prisma.PrismaClientKnownRequestError && reason.code === "P2025") return NextResponse.json({ error: "Empréstimo ou bem não encontrado." }, { status: 404 }); throw reason; }
async function available(tx: Prisma.TransactionClient, inventoryItemId: string, excludingId?: string) { const item = await tx.inventoryItem.findUnique({ where: { id: inventoryItemId } }); if (!item || !item.active) throw new Error("ITEM_UNAVAILABLE"); const borrowed = await tx.rental.aggregate({ where: { inventoryItemId, status: "BORROWED", ...(excludingId ? { id: { not: excludingId } } : {}) }, _sum: { quantity: true } }); return { item, available: item.quantity - (borrowed._sum.quantity || 0) }; }

export async function GET(request: NextRequest) { const auth = await requireAdminApi(request); if (auth.error) return auth.error; return routeResponse(request, { items: await prisma.rental.findMany({ include: { inventoryItem: true }, orderBy: { dueAt: "desc" } }) }); }
export async function POST(request: NextRequest) { const auth = await requireAdminApi(request); if (auth.error || !auth.user) return auth.error!; try { const value = schema.parse(await requestData(request)); const item = await prisma.$transaction(async (tx) => { const stock = await available(tx, value.inventoryItemId); if (value.quantity > stock.available) throw new Error("INSUFFICIENT_STOCK"); return tx.rental.create({ data: { inventoryItemId: stock.item.id, itemName: stock.item.name, ...cleanData(value, auth.user.name), status: "BORROWED", createdBy: auth.user.name } }); }); await recordActivity(auth.user, "rental", item.id, "CREATED", { item: item.itemName, quantity: item.quantity }); return routeResponse(request, { item }, 201, "/admin/aluguel"); } catch (reason) { if (reason instanceof Error && reason.message === "INSUFFICIENT_STOCK") return NextResponse.json({ error: "Quantidade indisponível para empréstimo." }, { status: 409 }); if (reason instanceof Error && reason.message === "ITEM_UNAVAILABLE") return NextResponse.json({ error: "Selecione um bem ativo do patrimônio." }, { status: 409 }); if (reason instanceof Error && reason.message === "INVALID_DATES") return NextResponse.json({ error: "A devolução prevista não pode ser anterior à retirada." }, { status: 400 }); return invalid(reason); } }
export async function PUT(request: NextRequest) { const auth = await requireAdminApi(request); if (auth.error || !auth.user) return auth.error!; try { const raw = await requestData(request); const id = z.string().min(1).parse(raw.id); const value = schema.parse(raw); const item = await prisma.$transaction(async (tx) => { const existing = await tx.rental.findUnique({ where: { id } }); if (!existing || existing.status !== "BORROWED") throw new Error("CLOSED_RENTAL"); const stock = await available(tx, value.inventoryItemId, id); if (value.quantity > stock.available) throw new Error("INSUFFICIENT_STOCK"); return tx.rental.update({ where: { id }, data: { inventoryItemId: stock.item.id, itemName: stock.item.name, ...cleanData(value, auth.user.name) } }); }); await recordActivity(auth.user, "rental", id, "UPDATED", { item: item.itemName }); return routeResponse(request, { item }, 200, "/admin/aluguel"); } catch (reason) { if (reason instanceof Error && reason.message === "CLOSED_RENTAL") return NextResponse.json({ error: "Empréstimos devolvidos não podem ser alterados." }, { status: 409 }); if (reason instanceof Error && reason.message === "INSUFFICIENT_STOCK") return NextResponse.json({ error: "Quantidade indisponível para empréstimo." }, { status: 409 }); if (reason instanceof Error && reason.message === "ITEM_UNAVAILABLE") return NextResponse.json({ error: "Selecione um bem ativo do patrimônio." }, { status: 409 }); if (reason instanceof Error && reason.message === "INVALID_DATES") return NextResponse.json({ error: "A devolução prevista não pode ser anterior à retirada." }, { status: 400 }); return invalid(reason); } }
export async function PATCH(request: NextRequest) { const auth = await requireAdminApi(request); if (auth.error || !auth.user) return auth.error!; try { const raw = await requestData(request); const id = z.string().min(1).parse(raw.id); const returnNote = z.string().max(2000).nullable().optional().parse(raw.returnNote); const item = await prisma.$transaction(async (tx) => { const existing = await tx.rental.findUnique({ where: { id } }); if (!existing) throw new Error("NOT_FOUND"); if (existing.status === "RETURNED") throw new Error("ALREADY_RETURNED"); return tx.rental.update({ where: { id }, data: { status: "RETURNED", returnedAt: new Date(), returnedBy: auth.user.name, updatedBy: auth.user.name, conditionNote: clean(returnNote) || existing.conditionNote } }); }); await recordActivity(auth.user, "rental", id, "RETURNED", { item: item.itemName }); return NextResponse.json({ item }); } catch (reason) { if (reason instanceof Error && reason.message === "NOT_FOUND") return NextResponse.json({ error: "Empréstimo não encontrado." }, { status: 404 }); if (reason instanceof Error && reason.message === "ALREADY_RETURNED") return NextResponse.json({ error: "Este empréstimo já foi devolvido." }, { status: 409 }); return invalid(reason); } }
export async function DELETE(request: NextRequest) { const auth = await requireAdminApi(request); if (auth.error || !auth.user) return auth.error!; try { const id = z.string().min(1).parse((await requestData(request)).id); const existing = await prisma.rental.findUnique({ where: { id } }); if (!existing) return NextResponse.json({ error: "Empréstimo não encontrado." }, { status: 404 }); if (existing.status === "BORROWED") return NextResponse.json({ error: "Dê baixa na devolução antes de excluir o registro." }, { status: 409 }); await prisma.rental.delete({ where: { id } }); await recordActivity(auth.user, "rental", id, "DELETED", {}); return routeResponse(request, { ok: true }, 200, "/admin/aluguel"); } catch (reason) { return invalid(reason); } }
